In [1]:
# Add project root to path
import sys
from pathlib import Path

project_root = Path.cwd().parent  # Go up one level from notebooks/
sys.path.insert(0, str(project_root))

# Now import works
from tmp.build_ncaab_team_name_mapping_v2 import get_d1_team_matching_df

# Get the matching dataframe
df = get_d1_team_matching_df(season='2024-25', use_cache=True)

# Count stats
print(f"Total teams: {len(df)}")
print(f"Matched: {df['matched'].sum()}")
print(f"Unmatched: {(~df['matched']).sum()}")

# View all teams
df

Loading data for 2024-25...

📥 Loading game outcomes...
   📦 Loading from cache: /Users/thomasmyles/Downloads/tmp/ncaab_cache/outcomes_2024-11-03_2025-04-20.parquet
   ✅ Loaded 6299 games from cache

📥 Loading game lines...
   📦 Loading from cache: /Users/thomasmyles/Downloads/tmp/ncaab_cache/lines_2024-11-03_2025-04-20.parquet
   ✅ Loaded 5741 games from cache
Excluded non-D1 teams: 9
ESPN D1 teams (≥5 games): 364
Odds API teams: 364
Calculating ATS stats...

Results:
   Total D1 teams: 364
   Matched: 364 (100.0%)
   Unmatched: 0 (0.0%)
Total teams: 364
Matched: 364
Unmatched: 0

,team_name_espn,team_name_odds_api,matched,espn_games,espn_wins,espn_losses,espn_win_pct,ats_games,ats_wins,ats_losses,ats_pushes,ats_win_pct
0,Abilene Christian Wildcats,Abilene Christian Wildcats,True,32,16,16,0.500000,29,13,16,0,0.448276
1,Air Force Falcons,Air Force Falcons,True,32,4,28,0.125000,32,12,20,0,0.375000
2,Akron Zips,Akron Zips,True,35,28,7,0.800000,32,16,16,0,0.500000
3,Alabama A&M Bulldogs,Alabama A&M Bulldogs,True,32,10,22,0.312500,29,8,21,0,0.275862
4,Alabama Crimson Tide,Alabama Crimson Tide,True,37,28,9,0.756757,35,20,15,0,0.571429
...,...,...,...,...,...,...,...,...,...,...,...,...
359,Wright State Raiders,Wright St Raiders,True,33,15,18,0.454545,31,15,16,0,0.483871
360,Wyoming Cowboys,Wyoming Cowboys,True,32,12,20,0.375000,31,14,17,0,0.451613
361,Xavier Musketeers,Xavier Musketeers,True,34,22,12,0.647059,32,18,14,0,0.562500
362,Yale Bulldogs,Yale Bulldogs,True,30,22,8,0.733333,29,17,12,0,0.586207
363,Youngstown State Penguins,Youngstown St Penguins,True,35,21,14,0.600000,31,15,16,0,0.483871

In [2]:
# Filter to unmatched teams only
df[~df['matched']]

Empty DataFrame
Columns: [team_name_espn, team_name_odds_api, matched, espn_games, espn_wins, espn_losses, espn_win_pct, ats_games, ats_wins, ats_losses, ats_pushes, ats_win_pct]
Index: []

In [3]:
# Filter to matched teams only
df[df['matched']]

,team_name_espn,team_name_odds_api,matched,espn_games,espn_wins,espn_losses,espn_win_pct,ats_games,ats_wins,ats_losses,ats_pushes,ats_win_pct
0,Abilene Christian Wildcats,Abilene Christian Wildcats,True,32,16,16,0.500000,29,13,16,0,0.448276
1,Air Force Falcons,Air Force Falcons,True,32,4,28,0.125000,32,12,20,0,0.375000
2,Akron Zips,Akron Zips,True,35,28,7,0.800000,32,16,16,0,0.500000
3,Alabama A&M Bulldogs,Alabama A&M Bulldogs,True,32,10,22,0.312500,29,8,21,0,0.275862
4,Alabama Crimson Tide,Alabama Crimson Tide,True,37,28,9,0.756757,35,20,15,0,0.571429
...,...,...,...,...,...,...,...,...,...,...,...,...
359,Wright State Raiders,Wright St Raiders,True,33,15,18,0.454545,31,15,16,0,0.483871
360,Wyoming Cowboys,Wyoming Cowboys,True,32,12,20,0.375000,31,14,17,0,0.451613
361,Xavier Musketeers,Xavier Musketeers,True,34,22,12,0.647059,32,18,14,0,0.562500
362,Yale Bulldogs,Yale Bulldogs,True,30,22,8,0.733333,29,17,12,0,0.586207
363,Youngstown State Penguins,Youngstown St Penguins,True,35,21,14,0.600000,31,15,16,0,0.483871